<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.36.0" />
    <PackageReference Include="Grpc.Core.Api" Version="2.83.0" />
    <PackageReference Include="Grpc.Tools" Version="2.83.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Refit" Version="15.2.0" />
    <PackageReference Include="Refit.HttpClientFactory" Version="15.2.0" />
    <Protobuf Include="Protos\auction.proto" GrpcServices="Client" />
    <Protobuf Include="Protos\reasonabilityResults.proto" GrpcServices="Client" />
  </ItemGroup>

</Project>